; Song PoozMooz, tu pooz et ça Mooz... in Lightweight format (V1).
; Generated by Arkos Tracker 2.

song_SongStart
	defb "ATLW"	; Format marker (LightWeight).
	defb 1	; Format version.
	defw song_FmInstrumentTable
	defw song_ArpeggioTable
	defw song_PitchTable
; Table of the Subsongs.
	defw song_Subsong0

; The Arpeggio table.
song_ArpeggioTable
	defw 0

; The Pitch table.
song_PitchTable
	defw 0

; The FM Instrument table.
song_FmInstrumentTable
	defw song_FmInstrument0
	defw song_FmInstrument1
	defw song_FmInstrument2

song_FmInstrument0
	defb 255	; Speed.

song_FmInstrument0_Loop	defb 0	; Volume: 0.

	defb 4	; End the instrument.
	defw song_FmInstrument0_Loop	; Loops.

song_FmInstrument1
	defb 0	; Speed.

	defb 189	; Volume: 15.
	defb 25	; Arpeggio: 12.
	defb 11	; Noise: 11.

	defb 185	; Volume: 14.
	defb 27	; Arpeggio: 13.
	defb 10	; Noise: 10.

	defb 181	; Volume: 13.
	defb 33	; Arpeggio: 16.
	defb 9	; Noise: 9.

	defb 181	; Volume: 13.
	defb 19	; Arpeggio: 9.
	defb 8	; Noise: 8.

	defb 177	; Volume: 12.
	defb 1	; Arpeggio: 0.
	defb 7	; Noise: 7.

	defb 169	; Volume: 10.
	defb 19	; Arpeggio: 9.
	defb 6	; Noise: 6.

	defb 161	; Volume: 8.
	defb 29	; Arpeggio: 14.
	defb 5	; Noise: 5.

	defb 153	; Volume: 6.
	defb 1	; Arpeggio: 0.
	defb 4	; Noise: 4.

	defb 145	; Volume: 4.
	defb 1	; Arpeggio: 0.
	defb 3	; Noise: 3.

	defb 141	; Volume: 3.
	defb 1	; Arpeggio: 0.
	defb 2	; Noise: 2.

	defb 4	; End the instrument.
	defw song_FmInstrument0_Loop	; Loop to silence.

song_FmInstrument2
	defb 0	; Speed.

	defb 61	; Volume: 15.

	defb 57	; Volume: 14.

	defb 53	; Volume: 13.

	defb 49	; Volume: 12.

	defb 4	; End the instrument.
	defw song_FmInstrument0_Loop	; Loop to silence.

; Song PoozMooz, tu pooz et ça Mooz..., Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

song_Subsong0
	defb 6	; Initial speed.

; The Linker.
; Pattern 0
song_Subsong0_Loop
	defb 5	; State byte.
	defb 63	; New height.
	defw song_Subsong0_Track7, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 1
	defb 1	; State byte.
	defw song_Subsong0_Track0, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 2
	defb 1	; State byte.
	defw song_Subsong0_Track4, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 3
	defb 1	; State byte.
	defw song_Subsong0_Track2, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 4
	defb 1	; State byte.
	defw song_Subsong0_Track3, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 5
	defb 1	; State byte.
	defw song_Subsong0_Track5, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 6
	defb 1	; State byte.
	defw song_Subsong0_Track4, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 7
	defb 1	; State byte.
	defw song_Subsong0_Track2, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 8
	defb 1	; State byte.
	defw song_Subsong0_Track6, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 9
	defb 1	; State byte.
	defw song_Subsong0_Track8, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 10
	defb 1	; State byte.
	defw song_Subsong0_Track9, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

; Pattern 11
	defb 1	; State byte.
	defw song_Subsong0_Track10, song_Subsong0_Track1, song_Subsong0_Track1	; The tracks.

	defb 0	; End of the subsong.
	defw song_Subsong0_Loop

; The Tracks.
song_Subsong0_Track0
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 126	; Short wait: 2.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 21	; Escaped note: 21.
	defb 62	; Short wait: 1.

	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 62	; Short wait: 1.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 126	; Short wait: 2.

	defb 0	; Note: 24.
	defb 0	; Note: 24.
	defb 126	; Short wait: 2.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 126	; Short wait: 2.

	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 126	; Short wait: 2.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 2	; Note: 26.
	defb 62	; Short wait: 1.

	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 62	; Short wait: 1.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 14	; Note: 38.
	defb 21	; Note: 45.
	defb 62	; Short wait: 1.

	defb 19	; Note: 43.
	defb 16	; Note: 40.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 16	; Note: 40.
	defb 62	; Short wait: 1.

	defb 9	; Note: 33.
	defb 12	; Note: 36.
	defb 14	; Note: 38.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 135	; Note: 31.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.

song_Subsong0_Track1
	defb 61, 63	; Long wait: 64.


song_Subsong0_Track2
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 31	; Note: 55.
	defb 33	; Note: 57.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 63, 21	; Escaped note: 21.
	defb 43	; Note: 67.
	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 40	; Note: 64.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 40	; Note: 64.
	defb 43	; Note: 67.
	defb 0	; Note: 24.
	defb 0	; Note: 24.
	defb 33	; Note: 57.
	defb 31	; Note: 55.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 0	; Note: 24.
	defb 63, 72	; Escaped note: 72.
	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 40	; Note: 64.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 63, 72	; Escaped note: 72.
	defb 43	; Note: 67.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 31	; Note: 55.
	defb 36	; Note: 60.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 24	; Note: 48.
	defb 2	; Note: 26.
	defb 19	; Note: 43.
	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 21	; Note: 45.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 28	; Note: 52.
	defb 14	; Note: 38.
	defb 21	; Note: 45.
	defb 24	; Note: 48.
	defb 19	; Note: 43.
	defb 16	; Note: 40.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 63, 74	; Escaped note: 74.
	defb 16	; Note: 40.
	defb 45	; Note: 69.
	defb 9	; Note: 33.
	defb 12	; Note: 36.
	defb 14	; Note: 38.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 191, 72	; Escaped note: 72.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.

song_Subsong0_Track3
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 45	; Note: 69.
	defb 45	; Note: 69.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 63, 21	; Escaped note: 21.
	defb 63, 72	; Escaped note: 72.
	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 43	; Note: 67.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 33	; Note: 57.
	defb 45	; Note: 69.
	defb 0	; Note: 24.
	defb 0	; Note: 24.
	defb 45	; Note: 69.
	defb 45	; Note: 69.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 0	; Note: 24.
	defb 63, 72	; Escaped note: 72.
	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 43	; Note: 67.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 63, 74	; Escaped note: 74.
	defb 43	; Note: 67.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 33	; Note: 57.
	defb 33	; Note: 57.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 28	; Note: 52.
	defb 2	; Note: 26.
	defb 31	; Note: 55.
	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 33	; Note: 57.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 31	; Note: 55.
	defb 33	; Note: 57.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 36	; Note: 60.
	defb 38	; Note: 62.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 31	; Note: 55.
	defb 2	; Note: 26.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 16	; Note: 40.
	defb 33	; Note: 57.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 159	; Note: 55.
	defb 4	; New instrument: 2.

song_Subsong0_Track4
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 31	; Note: 55.
	defb 33	; Note: 57.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 63, 21	; Escaped note: 21.
	defb 43	; Note: 67.
	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 40	; Note: 64.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 40	; Note: 64.
	defb 43	; Note: 67.
	defb 0	; Note: 24.
	defb 0	; Note: 24.
	defb 33	; Note: 57.
	defb 31	; Note: 55.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 0	; Note: 24.
	defb 63, 72	; Escaped note: 72.
	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 40	; Note: 64.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 63, 74	; Escaped note: 74.
	defb 63, 72	; Escaped note: 72.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 24	; Note: 48.
	defb 2	; Note: 26.
	defb 19	; Note: 43.
	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 21	; Note: 45.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 28	; Note: 52.
	defb 31	; Note: 55.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 38	; Note: 62.
	defb 40	; Note: 64.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 43	; Note: 67.
	defb 2	; Note: 26.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 16	; Note: 40.
	defb 9	; Note: 33.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.

song_Subsong0_Track5
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 45	; Note: 69.
	defb 45	; Note: 69.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 63, 21	; Escaped note: 21.
	defb 63, 72	; Escaped note: 72.
	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 63, 74	; Escaped note: 74.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 43	; Note: 67.
	defb 45	; Note: 69.
	defb 0	; Note: 24.
	defb 0	; Note: 24.
	defb 45	; Note: 69.
	defb 45	; Note: 69.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 0	; Note: 24.
	defb 63, 74	; Escaped note: 74.
	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 43	; Note: 67.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 40	; Note: 64.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 63, 81	; Escaped note: 81.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 63, 84	; Escaped note: 84.
	defb 2	; Note: 26.
	defb 63, 86	; Escaped note: 86.
	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 63, 79	; Escaped note: 79.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 63, 81	; Escaped note: 81.
	defb 63, 81	; Escaped note: 81.
	defb 14	; Note: 38.
	defb 9	; Note: 33.
	defb 19	; Note: 43.
	defb 16	; Note: 40.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 16	; Note: 40.
	defb 43	; Note: 67.
	defb 9	; Note: 33.
	defb 45	; Note: 69.
	defb 45	; Note: 69.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 135	; Note: 31.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.

song_Subsong0_Track6
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 45	; Note: 69.
	defb 45	; Note: 69.
	defb 43	; Note: 67.
	defb 9	; Note: 33.
	defb 45	; Note: 69.
	defb 63, 21	; Escaped note: 21.
	defb 63, 74	; Escaped note: 74.
	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 43	; Note: 67.
	defb 45	; Note: 69.
	defb 9	; Note: 33.
	defb 63, 72	; Escaped note: 72.
	defb 45	; Note: 69.
	defb 0	; Note: 24.
	defb 0	; Note: 24.
	defb 26	; Note: 50.
	defb 28	; Note: 52.
	defb 31	; Note: 55.
	defb 12	; Note: 36.
	defb 28	; Note: 52.
	defb 0	; Note: 24.
	defb 26	; Note: 50.
	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 26	; Note: 50.
	defb 28	; Note: 52.
	defb 12	; Note: 36.
	defb 26	; Note: 50.
	defb 21	; Note: 45.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 14	; Note: 38.
	defb 24	; Note: 48.
	defb 2	; Note: 26.
	defb 26	; Note: 50.
	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 24	; Note: 48.
	defb 21	; Note: 45.
	defb 14	; Note: 38.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 26	; Note: 50.
	defb 33	; Note: 57.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 154	; Note: 50.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 144	; Note: 40.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 144	; Note: 40.
	defb 4	; New instrument: 2.
	defb 9	; Note: 33.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 9	; Note: 33.

song_Subsong0_Track7
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 126	; Short wait: 2.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 21	; Escaped note: 21.
	defb 62	; Short wait: 1.

	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 62	; Short wait: 1.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 126	; Short wait: 2.

	defb 0	; Note: 24.
	defb 0	; Note: 24.
	defb 126	; Short wait: 2.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 126	; Short wait: 2.

	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 126	; Short wait: 2.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 2	; Note: 26.
	defb 62	; Short wait: 1.

	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 62	; Short wait: 1.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 126	; Short wait: 2.

	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 126	; Short wait: 2.

	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 2	; Note: 26.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 16	; Note: 40.
	defb 9	; Note: 33.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.

song_Subsong0_Track8
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 45	; Note: 69.
	defb 45	; Note: 69.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 63, 21	; Escaped note: 21.
	defb 63, 74	; Escaped note: 74.
	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 43	; Note: 67.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 191, 72	; Escaped note: 72.
	defb 4	; New instrument: 2.
	defb 45	; Note: 69.
	defb 0	; Note: 24.
	defb 0	; Note: 24.
	defb 26	; Note: 50.
	defb 28	; Note: 52.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 28	; Note: 52.
	defb 0	; Note: 24.
	defb 26	; Note: 50.
	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 26	; Note: 50.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 154	; Note: 50.
	defb 4	; New instrument: 2.
	defb 21	; Note: 45.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 24	; Note: 48.
	defb 2	; Note: 26.
	defb 26	; Note: 50.
	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 24	; Note: 48.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 19	; Note: 43.
	defb 21	; Note: 45.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 26	; Note: 50.
	defb 33	; Note: 57.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 154	; Note: 50.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 144	; Note: 40.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 144	; Note: 40.
	defb 4	; New instrument: 2.
	defb 9	; Note: 33.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 9	; Note: 33.

song_Subsong0_Track9
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 9	; Note: 33.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 137	; Note: 33.
	defb 4	; New instrument: 2.
	defb 21	; Note: 45.
	defb 21	; Note: 45.
	defb 0	; Note: 24.
	defb 0	; Note: 24.
	defb 12	; Note: 36.
	defb 12	; Note: 36.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 24	; Note: 48.
	defb 0	; Note: 24.
	defb 12	; Note: 36.
	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 12	; Note: 36.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 24	; Note: 48.
	defb 24	; Note: 48.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 14	; Note: 38.
	defb 14	; Note: 38.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 26	; Note: 50.
	defb 2	; Note: 26.
	defb 14	; Note: 38.
	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 26	; Note: 50.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 26	; Note: 50.
	defb 26	; Note: 50.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 14	; Note: 38.
	defb 14	; Note: 38.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 142	; Note: 38.
	defb 4	; New instrument: 2.
	defb 26	; Note: 50.
	defb 2	; Note: 26.
	defb 16	; Note: 40.
	defb 19	; Note: 43.
	defb 16	; Note: 40.
	defb 9	; Note: 33.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.

song_Subsong0_Track10
	defb 191, 21	; Escaped note: 21.
	defb 4	; New instrument: 2.
	defb 63, 21	; Escaped note: 21.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 45	; Note: 69.
	defb 9	; Note: 33.
	defb 21	; Note: 45.
	defb 63, 21	; Escaped note: 21.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 63, 21	; Escaped note: 21.
	defb 9	; Note: 33.
	defb 43	; Note: 67.
	defb 9	; Note: 33.
	defb 21	; Note: 45.
	defb 21	; Note: 45.
	defb 0	; Note: 24.
	defb 12	; Note: 36.
	defb 12	; Note: 36.
	defb 12	; Note: 36.
	defb 40	; Note: 64.
	defb 12	; Note: 36.
	defb 24	; Note: 48.
	defb 0	; Note: 24.
	defb 12	; Note: 36.
	defb 12	; Note: 36.
	defb 0	; Note: 24.
	defb 24	; Note: 48.
	defb 43	; Note: 67.
	defb 12	; Note: 36.
	defb 45	; Note: 69.
	defb 24	; Note: 48.
	defb 2	; Note: 26.
	defb 2	; Note: 26.
	defb 14	; Note: 38.
	defb 14	; Note: 38.
	defb 63, 72	; Escaped note: 72.
	defb 14	; Note: 38.
	defb 26	; Note: 50.
	defb 2	; Note: 26.
	defb 14	; Note: 38.
	defb 14	; Note: 38.
	defb 2	; Note: 26.
	defb 14	; Note: 38.
	defb 63, 74	; Escaped note: 74.
	defb 14	; Note: 38.
	defb 26	; Note: 50.
	defb 14	; Note: 38.
	defb 21	; Note: 45.
	defb 33	; Note: 57.
	defb 19	; Note: 43.
	defb 16	; Note: 40.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 154	; Note: 50.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 156	; Note: 52.
	defb 4	; New instrument: 2.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 14	; Note: 38.
	defb 137	; Note: 33.
	defb 2	; New instrument: 1.
	defb 9	; Note: 33.
	defb 9	; Note: 33.
	defb 9	; Note: 33.

